spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:tripmate}
    username: ${DB_USER:tripmate}
    password: ${DB_PASSWORD:10jeong}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    instance-id:
      ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}